#!/usr/bin/env bash
#
# Michael B. Kulik
# 6/6/2011
#
# deploy script for devious site
#

while getopts "pwfth" flag
do
    if [ "$flag" = "p" ]; then
        echo -e "Deploy Everything to Production"
        break
    fi
    
    if [ "$flag" = "w" ]; then
        echo -e "Deploy Just html files"
    fi

    if [ "$flag" = "f" ]; then
        echo -e "Deploy just folders"
    fi

    if [ "$flag" = "t" ]; then
        echo -e "Test mode"
    fi

    if [ "$flag" = "h" ]; then
        echo -e "usage: $0 {p|w|f||t|h}\np -> production\nt -> testing"
    fi
done

#if [ $doAll -eq 1 ]; then
#    echo -e "Do All\n"
#    #scp -r *.html css/ images/ mk@devio.us:/home/mk/public_html/
#elif [ $doHtml = 1 | $doFolders = 1 ]; then
#    echo -e "Do html or Folders\n"
#    #scp -r *.html mk@devio.us/home/mk/public_html/
#elif [ $doTesting = 1 ]; then
#    if [ `uname` = "Darwin" ]; then
#        open index.html
#    else
#        xdg-open index.html
#    fi
#else
#    echo -e "usage: $0 {h|f|a|t}\np -> production\nt -> testing"
#fi
