#!/usr/bin/env bash
#
# Michael B. Kulik
# 6/6/2011
#
# deploy script for devious site
#
# use git-diff --name-only to get a list of changed files for pushing to 
# devious

doProduction=0
doTesting=0

while getopts "pt" flag
do
    if [ "$flag" = "p" ]; then
        doProduction=1
    fi

    if [ "$flag" = "t" ]; then
        doTesting=1
    fi
done

if [ $doProduction = 1 ]; then
    if [ ! -d "staging" ]; then
        mkdir staging
    fi

    topush=`git diff --name-only`
    for file in $topush
    do
        echo "Copying $file to staging directory"
        cp -R $file staging/
    done


elif [ $doTesting = 1 ]; then
    if [ `uname` = "Darwin" ]; then
        open index.html
    else
        xdg-open index.html
    fi
else
    echo -e "usage: $0 {p|t}\np -> production\nt -> testing"
fi
