#!/bin/sh
#
# Michael B. Kulik
# 6/6/2011
#
# deploy script for devious site
#

state=$1
platform=`uname`

case "$state" in
'devel')
	if [ "$platform" = "Darwin" ]; then
		open index.html
    	else
		xdg-open index.html
	fi
	;;
'production')
	scp *.html *.ico *.css mk@devio.us:/home/mk/public_html/
	;;
*)
	echo "$0 {devel|production}"
	exit 1
	;;
esac
